global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'stoll-ai'
    static_configs:
      - targets: ['stoll-ai:9090']
    scrape_interval: 5s
    metrics_path: /metrics
    
  - job_name: 'stoll-ai-api'
    static_configs:
      - targets: ['stoll-ai-api:8001']
    scrape_interval: 5s
    metrics_path: /metrics
    
  - job_name: 'talos-backend'
    static_configs:
      - targets: ['talos-backend:5000']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 10s
